feat(discord): [OWL-26532861] implement give command
devthena/little-owl pull request #20
Opened 2023-05-04 09:07 UTC by alvinb

2023-05-04 21:18 UTC, devthena requested changes

2023-05-04 21:18 UTC, devthena commented on src/discord/commands/give.ts
> +    if (isNaN(amount)) {
Do we still need this block if we are already using `.addNumberOption` for the `amount` input?

2023-05-04 21:18 UTC, devthena commented on src/discord/commands/give.ts
> +    if (amount <= 0) {
Just me being nit-picky, can we make the condition `amount < 1` lol

2023-05-04 21:18 UTC, devthena commented on src/discord/commands/give.ts
> +    // @to-do: check if recipient goes will exceed max points before giving
I don't think we plan to add a max point for users so we don't have to do this check

2023-05-04 21:27 UTC, devthena commented on src/discord/commands/give.ts
> +    const replies = {
Let's make it so all replies that are not `success` will be returned as ephemeral on the `interaction.reply`

2023-05-04 21:30 UTC, devthena commented
Sorry, one last thing, can you make it so PR title is capitalized please?

2023-05-05 03:52 UTC, alvinb commented on src/discord/commands/give.ts
> +    recipientData: DiscordUserProps
addressed here: https://github.com/devthena/little-owl/pull/20/commits/856a4fcca3615a320a231425c094ac5109b63840

2023-05-05 03:52 UTC, alvinb commented on src/discord/commands/give.ts
> +    if (isNaN(amount)) {
removed. addressed here: https://github.com/devthena/little-owl/pull/20/commits/856a4fcca3615a320a231425c094ac5109b63840

2023-05-05 03:52 UTC, alvinb commented on src/discord/commands/give.ts
> +    // @to-do: check if recipient goes will exceed max points before giving
removed here: https://github.com/devthena/little-owl/pull/20/commits/856a4fcca3615a320a231425c094ac5109b63840

2023-05-05 03:52 UTC, alvinb commented on src/discord/commands/give.ts
> +    if (amount <= 0) {
updated here: https://github.com/devthena/little-owl/pull/20/commits/856a4fcca3615a320a231425c094ac5109b63840

2023-05-05 03:53 UTC, alvinb commented on src/discord/events/interactionCreate.ts
> +import { CoinFlip, EightBall, Gamble, Help, Points, Give } from '../commands';
updated here: https://github.com/devthena/little-owl/pull/20/commits/856a4fcca3615a320a231425c094ac5109b63840

2023-05-05 03:53 UTC, alvinb commented on src/discord/commands/give.ts
> +    const replies = {
addressed here: https://github.com/devthena/little-owl/pull/20/commits/856a4fcca3615a320a231425c094ac5109b63840

2023-05-05 05:20 UTC, devthena commented on src/discord/events/interactionCreate.ts
> +  Give,
Let's move this line after `Gamble` to make it alphabetical

2023-05-05 05:54 UTC, alvinb commented on src/discord/events/interactionCreate.ts
> +  Give,
done

2023-05-05 08:10 UTC, devthena approved these changes

2023-05-05 20:38 UTC, merged