feat(discord, twitch): [OWL-27896248] append current balance to on success messages
devthena/little-owl pull request #26
Opened 2023-05-13 05:30 UTC by alvinb

- appends "Your current balance `{amount}`" when users successfully gives money or when they win using the gamble command

2023-05-13 22:18 UTC, devthena requested changes

2023-05-13 22:18 UTC, devthena commented on src/discord/commands/gamble.ts
> +          content: `You won ${user.cash} ${CONFIG.CURRENCY.PLURAL}! :moneybag: Your cash balance: ${points} :coin:.`,
Let's remove the period at the end of the sentence for all of them

2023-05-13 22:18 UTC, devthena commented on src/discord/commands/give.ts
> +        { $set: { points: (recipient.cash += amount) } }
We should keep the `cash` key the same. We removed `points` from the new collection

2023-05-13 22:18 UTC, devthena commented on src/discord/commands/give.ts
> +        { $set: { points: (user.cash -= amount) } }
Same as above

2023-05-14 18:43 UTC, alvinb commented on src/discord/commands/give.ts
> +        { $set: { points: (recipient.cash += amount) } }
ohh whatta. i dont remember making this change. mustve been a merge error.
good catch

2023-05-14 21:20 UTC, devthena requested changes

2023-05-14 21:20 UTC, devthena commented on src/discord/commands/give.ts
> +      content: `${replies.success}. Your cash balance: ${user.cash} :coin:.`,
Let's also remove the period at the end for this

2023-05-14 21:20 UTC, devthena commented on src/twitch/commands/gamble.ts
> +        `${user.twitch_username} won ${user.cash} ${CONFIG.CURRENCY.PLURAL}! :moneybag: Your cash balance: ${points}.`
Same as above, let's remove all periods at the end of the `:coin:` emoji

2023-05-14 22:45 UTC, alvinb commented on src/twitch/commands/gamble.ts
> +        `${user.twitch_username} won ${user.cash} ${CONFIG.CURRENCY.PLURAL}! :moneybag: Your cash balance: ${points}.`
whoops forgot about this one. 

addressed it here: https://github.com/devthena/little-owl/pull/26/commits/3d2d891981174f9880b41a05ccc944fdd1b44956

2023-05-16 03:54 UTC, alvinb commented on src/discord/commands/give.ts
> +      content: `${replies.success}. Your cash balance: ${user.cash} :coin:.`,
whoops. addressed here:
https://github.com/devthena/little-owl/pull/26/commits/744a4c8f868019bc122da3c73a48740a73e170ce

2023-05-16 03:56 UTC, devthena approved these changes

2023-05-16 03:59 UTC, merged