feat(user-activity): [OWL-28298276] UserActivity and Star models
devthena/little-owl pull request #31
Opened 2023-05-20 23:18 UTC by alvinb

- Added models for `UserActivity` and `Star`
- Add methods for each model
- add collection names in `.env` file

2023-05-23 23:53 UTC, devthena commented on src/schemas/user-activity/star.ts
> +export interface Star {
Should we create a `src/interfaces` directory for all interfaces so it's all in one spot?

2023-05-23 23:53 UTC, devthena commented on src/schemas/user-activity/star.ts
> +        given_ds: format(new Date(), 'yyyy-MM-dd'),
I'm not sure if it's a typo, but let's make the date format consistent with either `YYYY-MM-DD` or `yyyy-mm-dd`.

2023-05-23 23:53 UTC, devthena commented on src/schemas/index.ts
> +export * from './user-activity';
Do you think we should rename the directory for this from `schemas` to `models` since we'll have classes too?

2023-05-23 23:53 UTC, devthena commented on src/schemas/user-activity/star.ts
> +    incrementTotal: (): number => {
If the increment is always gonna be 1, we can probably just directly make the database call for it

2023-05-23 23:53 UTC, devthena commented on src/schemas/user-activity/user-activity.ts
> +  user_id?: string;
Why is the `user_id` prop optional? Shouldn't it always have it?

2023-05-26 02:29 UTC, alvinb commented on src/schemas/index.ts
> +export * from './user-activity';
ohh. yeah lets rename it :)

2023-05-26 02:43 UTC, alvinb commented on src/schemas/user-activity/star.ts
> +export interface Star {
im a little torn bc having star interfaces in the `star.ts` is good in this case since some are just private to this file and only one is public so splitting them might cause confusion.

we can also make a dedicated `src/interfaces` directory though. just make everything public there. either way no strong opinion

2023-05-26 02:45 UTC, alvinb commented on src/schemas/user-activity/star.ts
> +        given_ds: format(new Date(), 'yyyy-MM-dd'),
oh this one is good. i took it from the example it their readme [here](https://github.com/date-fns/date-fns). good call out though

2023-05-26 02:56 UTC, alvinb commented on src/schemas/user-activity/user-activity.ts
> +  user_id?: string;
good catch. ill update

2023-06-03 22:13 UTC, devthena requested changes

2023-06-03 22:13 UTC, devthena commented on src/models/user-activity/star.ts
> +  let currentTotal = this.total.given || 0;
The value for `this.total.given` will always default to 0 so we don't have to check for nulls

2023-06-03 22:13 UTC, devthena commented on src/models/user-activity/star.ts
> +  this.total.given = ++currentTotal;
Instead of creating a `currentTotal` variable, can't we just directly set it like this to increment it:

`this.total.given += 1;`

2023-06-03 22:13 UTC, devthena commented on src/models/user-activity/user-activity.ts
> +import mongoose, { Schema } from 'mongoose';
Let's move this import at the top to make it alphabetical. Also, let's directly import `model` so it's consistent like the others:

`import { Schema, model } from 'mongoose';`

2023-06-03 22:13 UTC, devthena commented on src/models/user-activity/star.ts
> +import { Schema, model, Model } from 'mongoose';
Let's alphabetize how we're declaring the models:

`import { Model, Schema, model } from 'mongoose';`

2023-06-03 22:13 UTC, devthena commented on src/models/user-activity/user-activity.ts
> +connectToDatabase();
There should be no need to connect again to the database since we made the call in the `src/index.ts` file already and we never close the connection

2023-06-03 22:13 UTC, devthena commented on src/models/user/user.ts
> +import { Schema, model, Document } from 'mongoose';
Let's alphabetize how we're declaring this:

`import { Document, Schema, model } from 'mongoose';`

2023-06-03 22:13 UTC, devthena commented on src/models/user/user.ts
> +connectToDatabase();
Same as above, we shouldn't need to connect again to the database since the connection will always be open

2023-06-03 22:13 UTC, devthena commented on src/models/user/user.ts
> +  power_ups: object;
The `power_ups` should be a string[] and not an object

2023-06-03 22:13 UTC, devthena commented on src/models/user/user.ts
> +      type: Object,
Change this to String[] instead of Object

2023-06-03 22:14 UTC, devthena commented on src/schemas/user-activity/star.ts
> +export interface Star {
Yeah I'd want to make a dedicated `src/interfaces` directory. I'll make a separate ticket for this

2023-08-26 23:59 UTC, alvinb commented on src/schemas/user-activity/star.ts
> +export interface Star {
addressed here:
https://github.com/devthena/little-owl/pull/31/commits/e11c7dcdccd0526c6f7ea54d7e57f4c99ea8a36f

2023-08-26 23:59 UTC, alvinb commented on src/config/index.ts
> +export const appConfig = {
addressed here:
https://github.com/devthena/little-owl/pull/31/commits/e11c7dcdccd0526c6f7ea54d7e57f4c99ea8a36f

2023-08-27 00:07 UTC, alvinb commented on src/db/index.ts
> +export const connectToDatabase = async () => {
its generally good practice to have a separate folder for dbs as we can technically add multiple. ill move it back though

2023-08-27 00:10 UTC, devthena requested changes

2023-08-27 00:10 UTC, devthena commented on src/discord/commands/star.ts
> +import { STAR } from '../../config';
Let's move this config line before line 9 so it's alphabetical

2023-08-27 00:10 UTC, devthena commented on src/discord/commands/star.ts
> +      console.log('receipient', receipientUser);
This might be leftover from testing? We can remove the console logs

2023-11-10 06:58 UTC, alvinb commented on src/discord/events/interactionCreate.ts
> +    };
cant remove this just yet since it is being used by another command. should be removed when we refactor those commands

2023-11-10 07:13 UTC, devthena commented on src/discord/events/interactionCreate.ts
> +    // @todo: need to get rid of this in the future
What will be done here to get rid of this?

2023-11-10 07:13 UTC, devthena commented on src/discord/events/interactionCreate.ts
> +    // @todo: need to get rid of this in the future
Same with this one?

2023-11-10 07:13 UTC, devthena commented on src/discord/events/guildMemberAdd.ts
Did this file get reverted?

2023-11-10 07:23 UTC, devthena approved these changes

2023-11-10 07:27 UTC, merged